---
- hosts: localhost
  connection: local
  vars_files:
    - pass.yml  # Store AWS credentials securely
  tasks:
    - name: Start EC2 instance with a public IP
      amazon.aws.ec2_instance:
        name: "{{ item.name }}"
        key_name: "Ansible-key"
        instance_type: t2.micro
        security_groups: 
          - default
        region: ap-south-1
        aws_access_key: "{{ ec2_access_key }}"
        aws_secret_key: "{{ ec2_secret_key }}"
        network_interfaces:
          - assign_public_ip: true
        image_id: "{{ item.image }}"
      loop:
        - {  image: "ami-0d682f26195e9ec0f" , name: "manage-node-1"  }
        - {  image: "ami-00bb6a80f01f03502" , name: "manage-node-2"  }
        - {  image: "ami-00bb6a80f01f03502" , name: "manage-node-3"  }
